use proc_macro_util::{
    ast::{OuterAttribute, Type},
    tokens::Identifier,
};
use std::borrow::Cow;

mod from_input;
mod to_tokens;

/// A field in the struct definition being generated by the settings cache macro
pub struct SettingsCacheOutputStructField<'a> {
    /// The outer attributes on the field
    pub attributes: Vec<OuterAttribute<'a>>,

    /// The name of the field
    pub name: Cow<'a, Identifier>,

    /// The type of the field
    pub r#type: Type<'a>,
}
