[workspace]

[workspace.package]
version = "0.0.5"
authors = ["Lance Hart <me@lancehart.ca>"]
edition = "2024"
repository = "https://github.com/shipsimfan/colosseum"
license = "GPL-3.0-or-later"
publish = false

[workspace.dependencies]
colosseum-macros.path = "macros"
colosseum-build.path = "build"

time.git = "https://github.com/shipsimfan/lib-time"

[package]
name = "colosseum"
description = "D3D11 Game Engine"

version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
colosseum-macros.workspace = true

time.workspace = true

win32 = { git = "https://github.com/shipsimfan/lib-win32", features = [
    "d3d11",
    "d3d11sdklayers",
    "dxgi1_3",
    "dxgidebug",
] }

argparse.git = "https://github.com/shipsimfan/lib-argparse"
data-format.git = "https://github.com/shipsimfan/lib-data-format"
json.git = "https://github.com/shipsimfan/lib-json"

[build-dependencies]
colosseum-build.workspace = true
