[package]
name = "colosseum"
description = "A game engine built on Alexandria"
version = "0.1.0"
edition = "2021"
authors = ["Lance Hart <me@lancehart>"]
repository = "https://github.com/shipsimfan/colosseum.git"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
alexandria.path = "../alexandria"
data-format.git = "https://github.com/shipsimfan/lib-data-format"
json.git = "https://github.com/shipsimfan/lib-json"
