[package]
name = "colosseum"
version = "0.0.1"
description = "D3D11 Game Engine"
authors = ["Lance Hart <me@lancehart.ca>"]
edition = "2024"
repository = "https://github.com/shipsimfan/colosseum"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
win32 = { git = "https://github.com/shipsimfan/lib-win32", features = [
    "d3d11",
    "d3d11sdklayers",
    "dxgi1_3",
] }
argparse.git = "https://github.com/shipsimfan/lib-argparse"
