[package]
name = "colosseum-core"
description = "Core definitions for Colosseum"

version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
alexandria.workspace = true
argparse.workspace = true
data-format.workspace = true
json.workspace = true
time.workspace = true
