[package]
name = "colosseum-macros"
description = "Procedural macros for Colosseum"

version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro-util.git = "https://github.com/shipsimfan/lib-proc-macro-util"

win32 = { git = "https://github.com/shipsimfan/lib-win32", features = [
    "d3dcompiler",
] }
